# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Brainspired

description: > # this means to ignore newlines until "baseurl:"
  Human Sciences, Humanities, Health, Tech
  Book summaries, Articles, personal stuff and whatever else comes to my mind
baseurl: "" # the subpath of your site, e.g. /blog
url: "brainspired.org" # the base hostname & protocol for your site, e.g. http://example.com
email: shapespin@gmail.com
author: Andra Liana Voinea
street_address: 
city: 
state: 
zip_code:
country:
phone: 

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url:
instagram_url:
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 



# Build settings
destination: docs
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - [CNAME]
keep_files: [CNAME]
